name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r .next/standalone/.next deploy/
          cp -r .next/standalone/package.json deploy/
          cp -r .next/standalone/node_modules deploy/
          cp -r .next/static deploy/.next/
          cp .next/standalone/server.js deploy/
          ls -la deploy/

      - name: Copy files to GCE VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "/var/www/server/test-next-app"
          strip_components: 1
          
      - name: Restart PM2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/server/test-next-app
            if pm2 list | grep -q "test-next-app"; then
              pm2 delete test-next-app
            fi
            NODE_ENV=production PORT=3000 pm2 start server.js --name test-next-app